#!/bin/zsh

source "$HOME/scripts/utils/ensure_installed.sh"
source "$HOME/scripts/utils/ensure_reachable.sh"

# SSH into environment and copy password to clipboard w/ bitwarden-cli
ensure_installed bw

if [ "$SYSTEM_TYPE" = "Darwin" ]; then
	ensure_installed pbcopy
	copy_command=pbcopy
else
	ensure_installed wl-copy
	copy_command=wl-copy
fi

env=$1

bw get item "$env" &> /dev/null || {
	echo "No Bitwarden entry for $env"
	exit 1
}

url=$(bw get uri "$env" | cut -f3 -d/)

ensure_reachable $url

user=$(bw get username "$env")
password=$(bw get password "$env")

echo "$password" | $copy_command
echo "Copied saved password for environment $env to clipboard"
ssh "$user"@"$url"
