#!/bin/zsh

source "utils/ensure_installed.sh"

# SSH into environment and copy password to clipboard w/ lastpass-cli
ensure_installed lpass

env=$1-mysql

lpass show "$env" &> /dev/null || {
	echo "No LastPass entry for $env"
	exit 1
}

url=$(lpass show --url "$env" | cut -f3 -d/)
user=$(lpass show --username "$env")
password=$(lpass show --password "$env")

mysql -h "$url" -u "$user" -p"$password"
