#!/bin/zsh

# SSH into environment and copy password to clipboard w/ lastpass-cli
if ! command -v lpass &> /dev/null; then
	echo "lastpass-cli not installed"
	exit 1
fi

env=$1-mysql

lpass show "$env" &> /dev/null || {
	echo "No LastPass entry for $env"
	exit 1
}

url=$(lpass show --url "$env" | cut -f3 -d/)
user=$(lpass show --username "$env")
password=$(lpass show --password "$env")

mysql -h "$url" -u "$user" -p"$password"
