#!/bin/zsh

set -e

source "$HOME/scripts/utils/ensure_installed.sh"

# Resamples all flac files in current directory to 16-bit 44.1 kHz
ensure_installed sox

if [ $(find -maxdepth 1 -type f \( -name "*.flac" -or -name "*.wav" \) | wc -l) = 0 ]; then
	echo "no .flac or .wav files in current directory"
	exit 1
fi

mkdir resampled
find -maxdepth 1 -type f \( -name "*.flac" -or -name "*.wav" \) -exec zsh -c 'sox -S $1 -r 44100 -b 16 resampled/"$(basename $1 | sed "s/.*\///g" | sed "s/\.[^.]*$//").flac"' zsh {} \;

find -maxdepth 1 -type f \( -name "*.flac" -or -name "*.wav" \) -exec rm {} \;
mv resampled/* .
rm -r resampled
