#!/bin/zsh

# Resamples all flac files in current directory to 16-bit 44.1 kHz
if ! command -v sox &> /dev/null; then
	echo "sox is not installed"
	exit 1
fi

if [ $(find -maxdepth 1 -type f -name "*.flac" | wc -l) = 0 ]; then
	echo "no .flac files in current directory"
	exit 1
fi

mkdir resampled
for flac in *.flac; do
	sox -S "${flac}" -r 44100 -b 16 ./resampled/"${flac}"
done
rm *.flac
mv resampled/* .
rm -r resampled
