#!/bin/zsh

source "utils/ensure_installed.sh"

# SSH into environment and copy password to clipboard w/ lastpass-cli
ensure_installed lpass

if [ "$SYSTEM_TYPE" = "Darwin" ]; then
	ensure_installed pbcopy
	copy_command=pbcopy
else
	ensure_installed wl-copy
	copy_command=wl-copy
fi

env=$1

lpass show "$env" &> /dev/null || {
	echo "No LastPass entry for $env"
	exit 1
}

url=$(lpass show --url "$env" | cut -f3 -d/)

ping $url -c 1 &> /dev/null || {
	echo "Unable to reach target server. Does a VPN need to be connected?"
	exit 1
}

user=$(lpass show --username "$env")
password=$(lpass show --password "$env")

echo "$password" | $copy_command
echo "Copied sudo password for environment $env to clipboard"
ssh "$user"@"$url"
