#!/bin/zsh

# SSH into environment and copy password to clipboard w/ lastpass-cli
if ! command -v lpass &> /dev/null; then
	echo "lastpass-cli not installed"
	exit 1
fi

if [ "$SYSTEM_TYPE" = "Darwin" ]; then
	if ! command -v pbcopy &> /dev/null; then
		echo "pbcopy not installed"
		exit 1
	fi
	copy_command=pbcopy
else
	if ! command -v wl-copy &> /dev/null; then
		echo "wl-clipboard not installed"
		exit 1
	fi
	copy_command=wl-copy
fi

env=$1

lpass show "$env" &> /dev/null || {
	echo "No LastPass entry for $env"
	exit 1
}

url=$(lpass show --url "$env" | cut -f3 -d/)

ping $url -c 1 &> /dev/null || {
	echo "Unable to reach target server. Does a VPN need to be connected?"
	exit 1
}

user=$(lpass show --username "$env")
password=$(lpass show --password "$env")

echo "$password" | $copy_command
echo "Copied sudo password for environment $env to clipboard"
ssh "$user"@"$url"
